# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID2020
pod 'Charts', '~> 3.4'

end
